image: debian/stable
sources:
    - https://github.com/peterbourgon/usage
tasks:
    - go_toolchain: |
        wget -q https://dl.google.com/go/go1.12.6.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.12.6.linux-amd64.tar.gz
        sudo ln -s /usr/local/go/bin/go /usr/bin/go
        go env
    - dependencies: |
        mkdir -p $HOME/go/src/github.com/peterbourgon
        mv usage $HOME/go/src/github.com/peterbourgon
        go get -t github.com/peterbourgon/usage
    - test: |
        go test -race -v github.com/peterbourgon/usage/...
